# Generated by Django 2.0.5 on 2018-05-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtdUser',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=40, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, db_column='USER_EMAIL', max_length=40, null=True)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=80)),
                ('user_password', models.CharField(db_column='USER_PASSWORD', max_length=40)),
                ('user_phone', models.CharField(blank=True, db_column='USER_PHONE', max_length=15, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=2000, null=True)),
                ('user_status', models.IntegerField(blank=True, db_column='USER_STATUS', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='CREATE_TIME', null=True)),
                ('modify_time', models.DateTimeField(blank=True, db_column='MODIFY_TIME', null=True)),
                ('data_state', models.IntegerField(blank=True, db_column='DATA_STATE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ctd_user',
            },
        ),
    ]
